# ./.github/workflows/deploy.workflow.yml

name: deploy-workflow
on: [push] # [A]
jobs:
  deploy-job:
    runs-on: ubuntu-latest # [B]
    steps:
      - uses: actions/checkout@v2 # [C]
      - uses: actions/setup-node@v2 # [D]
        with:
          node-version: '16.15'
      - uses: actions/cache@v2 # [H]
        with:
         path: ${{ github.workspace }}/node_modules
         key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}
         
      - run: npm install
      - run: npm run build
      - uses: stefanzweifel/git-auto-commit@action@v4
        with:
          commit_message: Automated publish
      
